### ISSUE TITLE
ModuleNotFoundError: No module named 'graphframes'

### ISSUE THREAD

**Issue by hepengfei-ml** [SalilJain/pyspark_dbscan#1]
ModuleNotFoundError: No module named 'graphframes'

**Comment by SalilJain** [comment]
@hepengfei-ml  Please install Graphframes https://pypi.org/project/graphframes/

I will add a requirements file in repo to resolve these issues in future.

**Comment by hepengfei-ml** [comment]
I've install graphframes . But there is this bug Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.6.0-spark2.4.7-s_2.11: not found]

**Comment by hepengfei-ml** [comment]
My environment 
graphframes==0.6
spark==2.4.7
python==3.6

**Comment by hepengfei-ml** [comment]
: java.lang.NoClassDefFoundError: com/typesafe/scalalogging/slf4j/LazyLogging

**Comment by SalilJain** [comment]
Please see https://github.com/graphframes/graphframes/issues/113 if that resolves your issue
